### ISSUE TITLE
Team Contract Creation

### ISSUE THREAD

**Issue by ansarusc** [UBC-MDS/525-group8#2]
Hi everyone,

For the creation of the team contract, it would be amazing if you could mention:

*  Expected number of reunions per week as well as a schedule proposal.
*  Any expectations or approaches when facing conflict you would like to include.
* Expected workflow ( branches or forks), organizing reunions, etc.

With this information, I´ll be able to structure the team contract.

**Comment by rachelywong** [comment]
- minimum 2 meetings per week (monday lab and before submission)
- democratic voting for any conflicts, communication from each person before making any major decisions
- everyone makes their own branch and we make a branch for each milestone, i've set up branch protection for our main branch so we should only push to main once we've all agreed
- time expectations, i can meet and communicate at any time, preferably before 9pm and after 8am though lol
- work expectations: everybody does their part and we can ask for help if we're unable to complete our task! please let us know in advance if you need help or have a time conflict for meetings!

**Comment by wang-rui** [comment]
Agree with what @rachelywong had above.

We can finish our own parts before the meetings for submissions so we can walk through everything. 

I'm not sure if we plan to submit the assignment together in the meeting or someone going to submit it? I personally prefer one person to submit on behalf of the team and this can be done on a rotation basis.

**Comment by danielon-5** [comment]
I'd suggest 3 meetings per week:
- During Monday's lab
- On Wednesday afternoon/evening once we've had lecture 2
- On Friday or Saturday to review everything and submit

I agree with Rachel's points regarding conflicts, decision making and communication.

My only time restrictions besides lectures and labs are:
- Tuesday's from 12 to 2pm
- Friday's from 12 to 4pm

I would also suggest to be rotating for meeting notes, specific milestone issue creation and submission every week.
