### ISSUE TITLE
2. Setup Jupyterhub

### ISSUE THREAD

**Issue by danielon-5** [UBC-MDS/525-group8#28]

**Comment by rachelywong** [comment]
Since I made the instance I have to set up JupyterHub but everybody needs to log in and @danielon-5 you take the screenshot

**Comment by danielon-5** [comment]
<img width="952" alt="525_jupyter_signin" src="https://user-images.githubusercontent.com/71201117/115061072-4986c800-9eae-11eb-8d9d-30192e86990c.png">
