### ISSUE TITLE
5. Submission

### ISSUE THREAD

**Issue by danielon-5** [UBC-MDS/525-group8#38]
SUBMISSION: Please put a link in canvas where TAs can find the following-

- [ ] Python 3 notebook, with the code for ML model in scikit-learn. (You can develop this on your existing jupyterHub in your EC2 instance, from milestone2)
- [ ] PySpark notebook, with the code for obtaining best hyperparameter settings. ( For this you have to use PySpark notebook in your EMR cluster )
-  Screenshot from:
    - [ ] Setup your EMR cluster (Task 1).
    - [ ] Setup your browser , jupyter environment & connect to the master node (Task 2).
    - [ ] Your S3 bucket showing model.joblib file. (From Task 3 Develop a ML model using scikit-learn)

**Comment by rachelywong** [comment]
- make sure screenshots are uploaded (also make sure the screenshots don't include IP addresses)
- make sure links to the other notebooks (tasks 3 and 4) work

**Comment by rachelywong** [comment]
SANTIAGOOOOO GO GO!!!!
