### ISSUE TITLE
Meeting notes April 19th LAB

### ISSUE THREAD

**Issue by danielon-5** [UBC-MDS/525-group8#39]
**Meeting notes**

We split the M3 tasks as follows:

1. Setup your EMR cluster - @rachelywong 
2. Setup your browser , jupyter environment & connect to the master node - @danielon-5 
3. Develop a ML model using scikit-learn - @ansarusc 
4. Obtain best hyperparameter settings using spark's MLlib - @wang-rui 
5. Submission - @ansarusc 

Upcoming meetings:

- Check-in Wednesday at 4:30pm
- Meeting on Friday (and submission 😏) 10am (12pm for daniel)

**Comment by danielon-5** [comment]
Tasks 1 and 2 have been covered. @wang-rui and @ansarusc let us know if you need any help with your tasks!

**Comment by rachelywong** [comment]
done!
