### ISSUE TITLE
R EDA location

### ISSUE THREAD

**Issue by ansarusc** [UBC-MDS/525-group8#4]
Hi Rui and Daniel,

With @rachelywong we suggest doing the R EDA inside the same Jupiter notebook using the `rpy2` package that is already included in the 525 yaml. Just be aware of this consideration.

**Comment by rachelywong** [comment]
I'll also be working on the R EDA! We can coordinate between us 3 here on how we want to split it up.

**Comment by danielon-5** [comment]
Sounds great @rachelywong and @ansarusc . Thanks for the update!
