### ISSUE TITLE
READme

### ISSUE THREAD

**Issue by rachelywong** [UBC-MDS/525-group8#6]
**Write brief introduction of the project in the README.**

During this course, you will be working on a team project involving big data. The purpose is to get exposure to working with much larger datasets than you have previously in MDS. You have been assigned to teams of three or four. (See group assignment in Canvas.) Unlike previous project courses, in this course, all of you will be working on the same problem. In particular, you will be building and deploying ensemble machine learning models in the cloud to predict daily rainfall in Australia on a large dataset (~12 GB), where features are outputs of different climate models and the target is the actual rainfall observation.

You will be using this dataset on figshare. The dataset has been put together by Tom. See [this notebook](PUT THE NOTEBOOK LINK) if you're interested in understanding how the data was prepared for you.

At the end of the project, you should have your ML model deployed in cloud for others to use.

During this course, you will work towards this goal step by step in four milestones.

Ideas:
- goal of project
- what our data is like
- why are we doing this
- packages used to perform the extraction and analysis
- small explanation of the API
- importance for large datasets

**Comment by rachelywong** [comment]
- link to the data (figshare)
- contributors --> all of our names + github username

**Comment by danielon-5** [comment]
The `m1_README` branch has the most up to date README file. I will create a PR to `milestone_1` branch. Please have a look and let me know about any changes you suggest.
