### ISSUE TITLE
Run Time and Memory Usage Discussion

### ISSUE THREAD

**Issue by wang-rui** [UBC-MDS/525-group8#8]
Hey guys,

Please help to note down your run times for `Combining data CSVs` step and share on the google spreadsheet below:

[Click to fill the spreadsheet](https://docs.google.com/spreadsheets/d/1oDbO_WcyTu35vPaV8FN4R4j0Z5D-w4CKR6kID39FFj0/edit?usp=sharing)

**Comment by rachelywong** [comment]
Just finishing up the code! Please run the entire notebook (`milestone_1.ipynb`) and post your computer specs, time, memory from the "Combining data CSVs using Pandas" section!

**Comment by ansarusc** [comment]
Hi Rach, did you combine the code with my branch´s code ?

**Comment by rachelywong** [comment]
@ansarusc yes! I'm just running everything from the top now until i push it

I'll send a note on slack once it finishes running!
